# Generated by Django 5.0.14 on 2026-07-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.TextField(max_length=50)),
                ("phone_number", models.TextField(max_length=18)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
