# Generated by Django 5.0.14 on 2026-07-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petmama", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=30)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "pet_type",
                    models.CharField(
                        choices=[("dog", "Dog"), ("cat", "Cat"), ("other", "Other")],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(max_length=200)),
            ],
        ),
    ]
