# Generated by Django 5.0.14 on 2026-08-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petmama", "0002_customercontact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkin_date", models.DateField()),
                ("checkout_date", models.DateField()),
                ("pet_name", models.TextField(max_length=21)),
                ("pet_age", models.PositiveBigIntegerField()),
                ("parent_name", models.TextField(max_length=21)),
                ("contact_number", models.TextField(max_length=14)),
                ("booking_email", models.EmailField(max_length=254)),
                (
                    "pet_type",
                    models.CharField(
                        choices=[("dog", "Dog"), ("cat", "Cat"), ("other", "Other")],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
